name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: "icons"

      - name: Configure Git
        run: |
          git config core.sparseCheckout true
          git remote add source https://github.com/tabler/tabler-icons.git

      - name: Fetch Source
        run: git fetch source main --depth=1

      - name: Checkout Source Files
        run: git checkout source/main -- icons

      - name: Install SVG Optimizer
        run: npm install -g svgo

      - name: Process SVG Files
        run: svgo -rf icons -o icons

      - name: Check for Changes
        id: check-changes
        run: |
          git add .
          echo "changes_exist=$(git status --porcelain | wc -l | xargs)" >> $GITHUB_OUTPUT

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SYNC_L10N_APP_ID }}
          private-key: ${{ secrets.SYNC_L10N_APP_PRIVATE_KEY }}
          owner: MahoCommerce

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes_exist != '0'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Updated icons and minified"
          title: "Icon Update $(date -u '+%Y-%m-%d')"
          body: |
            Automated changes include:
            - Latest icons from upstream
            - SVG optimization using SVGO
          branch: "icon-updates/$(date +%s)"
          base: main
          delete-branch: true
