name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: "icons"

      - name: Configure Git
        run: |
          git config core.sparseCheckout true
          git remote add upstream https://github.com/tabler/tabler-icons.git

      - name: Fetch Source
        run: git fetch upstream main --depth=1

      - name: Checkout Source Files
        run: git checkout upstream/main -- icons

      - name: Install SVG Optimizer
        run: npm install -g svgo

      - name: Process SVG Files
        run: svgo --config=.svgo.config.js -rf icons -o icons

      - name: Generate Branch Name
        id: branch
        run: echo "name=sync-upstream-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Check Changes
        id: changes
        run: |
          git add -A
          echo "has_changes=$(git diff --quiet HEAD || echo 'true')" >> $GITHUB_OUTPUT

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SYNC_L10N_APP_ID }}
          private-key: ${{ secrets.SYNC_L10N_APP_PRIVATE_KEY }}
          owner: MahoCommerce

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Updated and modified icons"
          title: "Sync Upstream"
          body: |
            Automated changes include:
            - Latest icons from upstream
            - SVG optimization using SVGO
          branch: ${{ steps.branch.outputs.name }}
          base: main
          delete-branch: true
